# Site
name: 'Programmingera'
description: 'Welcome to ProgrammingEra - Your Premier Destination for All Things Coding, Programming, and Technology. Stay ahead of the curve with expert insights, tutorials, and the latest industry news'
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: ''
disqus: 'programmingera'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

