name: "Programmingera"
websitename: "Programmingera.com"
title: "ProgrammingEra: Expert Insights, Tips, and Tricks for Programmers of All Levels"
description: "Welcome to ProgrammingEra - Your Premier Destination for All Things Coding, Programming, and Technology. Stay ahead of the curve with expert insights, tutorials, and the latest industry news"
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
baseurl:
siteurl: https://programmingera.com
url: https://programmingera.com
disqus: "programmingera"

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 12
paginate_path: "/latest/page/:num"

#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  authors:
    output: true
    permalink: /:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

sass:
  sass_dir: _sass
  style: compressed
