---
#-------------------------------
# Site Settings
title: "ProgrammingEra: Expert Insights, Tips, and Tricks for Programmers of All Levels"
description: "Welcome to ProgrammingEra - Your Premier Destination for All Things Coding, Programming, and Technology. Stay ahead of the curve with expert insights, tutorials, and the latest industry news"
logo: "/assets/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/assets/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Latest"
      url: "/latest/"
    - title: "Tags"
      url: "/tags"
    - title: "Our Story"
      url: "/about/"

# Call to action button
# cta_button:
#   enable: true
#   cta_button_link: '/contact/'
#   cta_button_text: Get in touch

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: "Programming Era: Your Online Coding Companion"
  hero_description: Explore various programming languages, topics, and challenges

#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  number_posts: 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  tags:
    - tag: "Technology"
    - tag: "web development"
    - tag: "coding"
    - tag: "programming"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.

#-------------------------------
# Authors Section Settings
authors_section:
  enable: true
  section_title: Meet our authors

#-------------------------------
# Footer Settings
footer_description: Explore the Universe of Programming with Programming Era

# Social Links
social:
# - {icon: "twitter", link: "https://twitter.com"}
# - {icon: "facebook", link: "https://facebook.com"}
# - {icon: "codepen", link: "https://codepen.io"}
# - {icon: "pinterest", link: "https://pinterest.com"}
# - {icon: "github", link: "https://github.com"}
# - {icon: "youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: true
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp_identifier:
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe

#-------------------------------
# Contact Settings
contact:
  email: wecanshapeofficial@gmail.com # Add your form_id
  description: Explore the Universe of Programming with Programming Era

#-------------------------------
# Comment Section (Disqus)
disqus_identifier: programmingera # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
google_analytics: G-WWTNXEV7C3
